APH1-58 Update blank.yml adding failure steps

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -18,7 +18,7 @@ jobs:
   # This workflow contains a single job called "build"
    build:
     # The type of runner that the job will run on
-    runs-on: 
+    runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -34,3 +34,10 @@ jobs:
         run: |
           echo Add other actions to build,
           echo test, and deploy your project.
+
+      # Fails the job forcing a Fail Build  
+      - name: Try to fail
+        run: exit 1
+
+      - name: Print message if we don't fail
+        run: echo Should not get here
